#!/bin/bash
# Program to check that mullvad is in use
# Martin Häggström 180908

MULLVAD_DNS_SERVER=193.138.218.169
MULLVAD_COUNTRY=Sweden
MULLVAD_BLACKLISTED=false

#DNS_SERVER=`curl -s https://am.i.mullvad.net/`
COUNTRY=`curl -s https://am.i.mullvad.net/country`
BLACKLISTED=`curl -s https://am.i.mullvad.net/json | jq .blacklisted.blacklisted`

if [ "${COUNTRY}" != "$MULLVAD_COUNTRY" ]
then
	echo "mullvad_is_not_working COUNTRY:${COUNTRY}" | wall
fi

if [ "$BLACKLISTED" != "$MULLVAD_BLACKLISTED" ]
then
	echo "mullvad_is_not_working BLACKLISTED:${BLACKLISTED}" | wall
fi
